config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :groups do
    resources :deals
  end
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get 'home', to: 'home#index', as: :home
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :deals

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :deals

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: true }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    # groups_path
    stored_location_for(resource) || groups_path
  end

  def after_sign_up_path_for(resource)
    # groups_path
    stored_location_for(resource) || groups_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    # Index action logic here
  end

  # GET /deals/new
  def new
    @group = Group.find(params[:group_id])
    @deal = @group.deals.build(user_id: current_user.id)
  end

  # POST /deals or /deals.json
  def create
    @deal = Deal.new(deal_params)
    @group = Group.find(params[:group_id])
    @deal.group = @group
    @deal.user = current_user # Assign the current user to the deal

    respond_to do |format|
      if @deal.save
        format.html { redirect_to group_path(@group), notice: 'Transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:author_id, :name, :amount, :created_at, :user_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show]

  # GET /groups or /groups.json
  def index
    @groups = Group.includes([:user]).where(user: current_user)
    @total_amounts = calculate_total_amounts(@groups)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @deal = Deal.new(group: @group)
    @total_amount = @group.deals.sum(:amount)
  end

  # GET /groups/new
  def new
    @group = current_user.groups.build
  end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.build(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to '/groups', notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :created_at)
  end

  def calculate_total_amounts(groups)
    total_amounts = {}
    groups.each do |group|
      total_amounts[group.id] = group.deals.sum(:amount)
    end
    total_amounts
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    # this is my splash page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/deals/_deal.html.erb
<div id="<%= dom_id deal%>" class="transacted-item">
  <div class="t-name p">
    <h4>Name</h4>
    <%= deal.name %>
  </div>

  <hr class="t-hr"/>

  <div class="t-created p">
    <h4>Transacted at</h4>
    <%= deal.created_at %>
  </div>

  <hr class="t-hr"/>

  <div class="t-amount t p">
    <h4>TOTAL PAYMENT</h4>
    <p>$<%= deal.amount %></p>
  </div>

</div>

app/views/deals/new.html.erb
<div class="nav-area">
    <div class="back-icon">
      <%= link_to group_path(@group) do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    </div>
    <div class="nav-details">
      <h2>Add New Category</h2>
    </div>
  </div>

<%= form_with(model: @deal, url: group_deals_path(@group), local: true) do |form| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% @deal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :categories %>
    <%= form.collection_select :group_id, current_user.groups, :id, :name, { prompt: "Select Category" }, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit "create transaction" %>
  </div>
<% end %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>

  <div>
    <%= form.label :created_at, style: "display: block" %>
    <%= form.datetime_field :created_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<%= link_to group_path(group) do %>
  <div id="<%= dom_id(group) %>" class="category">
    <img src="<%= group.icon %>" class="icon" />

    <div class="name-created">
      <div class="name">
        <%= group.name %>
      </div>
      <div class="created">
        <%= group.created_at %>
      </div>
    </div>

    <div class="total">
      $ <%= @total_amounts[group.id] || 0 %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="category-page">
  <div class="notice"><%= notice %></div>
  <div class="nav-area">
    <div class="c">
      <h2>CATEGORIES</h2>
    </div>
    <div class="logout">
      <% if user_signed_in? %>
        <form action="<%= destroy_user_session_path %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <button type="submit" class="btn btn-danger">Logout</button>
        </form>
      <% end %>
    </div>
  </div>

  <div id="groups" class="categories">
    <% @groups.each do |group| %>
      <%= render group %>
    <% end %>
  </div>
  <div class="add-category">
    <button class="new-category-btn">
      <%= link_to "ADD CATEGORY", new_group_path %>
    </button>
  </div>
</div>

app/views/groups/new.html.erb
<div class="new-category">
  <div class="nav-area">
    <div class="back-icon">
      <%= link_to groups_path do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    </div>
    <div class="nav-details">
      <h2>Add New Category</h2>
    </div>
  </div>

  <%= render "form", group: @group %>

</div>

app/views/groups/show.html.erb
<div class="transactions">
  <div class="nav-area">
    <div class="back-icon">
      <%= link_to groups_path do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    </div>
    <div class="nav-details">
      <h2><%= @group.name %> Transactions</h2>
      <p>Total Amount: <%= @total_amount %></p>
    </div>
  </div>

  <div class="deals-list">
    <% @group.deals.order(created_at: :desc).each do |deal| %>
      <%= render deal %>
    <% end %>
  </div>

  <button class="logins">
   <%= link_to "Add new transaction", new_group_deal_path(@group), class: "btn" %>
  </button>
</div>

app/views/home/index.html.erb
<div class="splash-page">
  <h1>BUDGET APP</h1>
  <div class="splash-buttons">
    <button class="logins">
      <%= link_to "LOG IN", user_session_path %>
    </button>
    <button class="logins">
      <%= link_to "SIGN UP", new_user_registration_path %>
    </button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>